
import __ASTRO_IMAGE_IMPORT_1f0j4j from "./images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_ZgI9zJ from "./images/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_Z1MrCeM from "./images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_1L12U6 from "./images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_fhzg3 from "./images/5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_Z1gqSo0 from "./images/6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_2i1LKS from "./images/7.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_Lij6P from "./images/8.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_ZJq9xd from "./images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_Z1bvDF1 from "./images/10.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_2mW1tR from "./images/11.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md";
import __ASTRO_IMAGE_IMPORT_GEo0K from "task-pic1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FTasks%2FScheduled-Tasks.md";
import __ASTRO_IMAGE_IMPORT_ZeLVdB from "task-pic2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FTasks%2FScheduled-Tasks.md";
import __ASTRO_IMAGE_IMPORT_Z1c3P7z from "sudo-pic1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FSudo%2FAbusing-Sudo.md";
export default new Map([["./images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_1f0j4j], ["./images/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_ZgI9zJ], ["./images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_Z1MrCeM], ["./images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_1L12U6], ["./images/5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_fhzg3], ["./images/6.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_Z1gqSo0], ["./images/7.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_2i1LKS], ["./images/8.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_Lij6P], ["./images/9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_ZJq9xd], ["./images/10.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_Z1bvDF1], ["./images/11.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FCertifications%2FeCPPTv3+-+eXam+Revision%2FeCPPT.md", __ASTRO_IMAGE_IMPORT_2mW1tR], ["task-pic1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FTasks%2FScheduled-Tasks.md", __ASTRO_IMAGE_IMPORT_GEo0K], ["task-pic2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FTasks%2FScheduled-Tasks.md", __ASTRO_IMAGE_IMPORT_ZeLVdB], ["sudo-pic1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FPrivilege+Escalation%2FSudo%2FAbusing-Sudo.md", __ASTRO_IMAGE_IMPORT_Z1c3P7z]]);
		